### ISSUE TITLE
multiple tags in search option?

### ISSUE THREAD

**Issue by sheksushant** [KarthikGangadhar/stack-exchange#2]
How can we pass multiple tags in search options?

```
let search_options = {
    "tagged": "javascript mongodb",
    "key": "",
    "pagesize" : 10,
    "filter":"!LUR8oAAZFxwopx_qXeHzCy",
    "access_token": ""
 }
```
the code above returns
{"items":[]}

while the code below returns the right response.

```
let search_options = {
    "tagged": "mongodb",
    "key": "Nd27jsEsv)Yhh2gkj*VZjA((",
    "pagesize" : 10,
    "filter":"!LUR8oAAZFxwopx_qXeHzCy",
    "access_token": ""
 }
```

**Comment by KarthikGangadhar** [comment]
As per the stack-exchange [search endpoint](https://api.stackexchange.com/docs/search)  documentation, tagged and nottagged fields are semi-colon delimited list of tags. you can pass multiple tags separated by semi-colon as follows:

```js

let search_options = {
    "tagged": "javascript;mongodb;",
    "key": "",
    "pagesize" : 10,
    "filter":"!LUR8oAAZFxwopx_qXeHzCy",
    "access_token": ""
 }

```

For example, see this search endpoint call for [java and python](https://api.stackexchange.com/2.2/search?order=desc&sort=activity&tagged=python;java&site=stackoverflow) tags
